machinetest/machinetest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace='web')),
    path('members/',include("members.urls",namespace='members')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machinetest/members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('login/',views.admin_login,name='admin_login'),

    path('add-member/',views.add_member,name="add_member"),
    path('edit-member/<str:id>/',views.edit_member,name="edit_member"),

    path('deactivate-member/<str:id>',views.deactivate_member,name="deactivate_member"),
    path('reactivate-member/<str:id>',views.reactivate_member,name="reactivate_member"),
    path('status-update/',views.multiple_member_status_update,name="muliple_member_status_update"),

    path('logout/',views.admin_logout,name='admin_logout'),

]

machinetest/web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [

    path('',views.index,name='index'),
    path('dashboard/',views.dashboard,name='dashboard'),

]

machinetest/templates/web/partials/sidebar.html
{% load static %}

<aside id="sidebar-wrapper">
    <div class="sidebar-brand">
        <img src="{% static 'web/images/logo.png' %}" class="logo" alt="">
    </div>

    <ul class="sidebar-nav">
        <li>
            <a href="#"><img src="{% static 'web/images/icons/home.png' %}" class="nav-icons" alt=""> Dashboard</a>
        </li>
        <li>
            <a href="#"><img src="{% static 'web/images/icons/airline.png' %}" class="nav-icons" alt=""> Airline
                Booking</a>
        </li>
        <li>
            <a href="#"><img src="{% static 'web/images/icons/orders.png' %}" class="nav-icons" alt=""> Enquiries &
                Orders</a>
        </li>

        <li class="active">
            <a href="#"><img src="{% static 'web/images/icons/members.png' %}" class="nav-icons" alt=""> Members</a>
        </li>
        <li>
            <a href="#"><img src="{% static 'web/images/icons/deal.png' %}" class="nav-icons" alt=""> Deals</a>
        </li>

        <li>
            <a href="#"><img src="{% static 'web/images/icons/service-provider.png' %}" class="nav-icons" alt="">
                Service Provider</a>
        </li>

        <li>
            <a href="#"><img src="{% static 'web/images/icons/service.png' %}" class="nav-icons" alt=""> Services</a>
        </li>
        <hr class="divider-line">

        <li>
            <a href="#"><img src="{% static 'web/images/icons/profile.png' %}" class="nav-icons" alt=""> Profile</a>
        </li>

        <li>
            <a href="{% url 'members:admin_logout' %}"><img src="{% static 'web/images/icons/logout.png' %}"
                    class="nav-icons" alt=""> Logout</a>
        </li>
    </ul>


</aside>