machinetest/machinetest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace='web')),
    path('members/',include("members.urls",namespace='members')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machinetest/members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('login/',views.admin_login,name='admin_login'),

    path('add-member/',views.add_member,name="add_member"),
    path('edit-member/<str:id>/',views.edit_member,name="edit_member"),

    path('deactivate-member/<str:id>',views.deactivate_member,name="deactivate_member"),
    path('reactivate-member/<str:id>',views.reactivate_member,name="reactivate_member"),
    path('status-update/',views.multiple_member_status_update,name="muliple_member_status_update"),

    path('logout/',views.admin_logout,name='admin_logout'),

]

machinetest/web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [

    path('',views.index,name='index'),
    path('dashboard/',views.dashboard,name='dashboard'),

]

machinetest/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'web/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">

</head>

<body id="dahboard-bg">

    <div id="wrapper">
        {% include 'web/partials/sidebar.html' %}

        {% block content %}

        {% endblock %}

    </div>

    <script src="{% static 'web/js/bootstrap/poper.js' %}"></script>
    <script src="{% static 'web/js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.js"
    integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>

    <!-- <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script> -->
    <script src="{% static 'web/js/script.js' %}"></script>

    {% block js %} {% endblock %}
</body>
</html>

machinetest/templates/web/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link rel="stylesheet" href="{% static 'web/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">


</head>

<body class="login-page">

    <main>

        <header>

            <nav class="navbar navbar-light ">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'web/images/logo.png' %}" class="applogo" alt="logo">
                    </a>
                </div>
            </nav>


        </header>

        <section>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">

                        <form class="login-form mx-auto row" method="POST" action="{% url 'members:admin_login' %}">
                            {% csrf_token %}
                            <div class="col-12">
                                <h1 class="login-title">Login</h1>
                                <p class="login-subtitle">Please login to your account</p>
                            </div>
                            <div class="mb-3 col-12">
                                <label for="username" class="form-label">Username</label>
                                <input type="email" name="username" class="form-control cstm-frm-cntrl" id="username"
                                    aria-describedby="emailHelp" required>

                            </div>

                            <div class="mb-3 col-12">
                                <label for="Password" class="form-label">Password</label>
                                <input type="password" name="password" class="form-control cstm-frm-cntrl" id="Password" required>
                            </div>
                            <div class="col-12 py-2">
                                <a href="#" class="forgotpswd-link">Forgot Password?</a>
                            </div>

                            <div class="col-12 text-center">
                                {% for message in messages %}
                                <small class="text-danger">{{message.message}} </small>
                                {% endfor %}
							</div>
                           

                            <div class="col-12 pt-2">

                                <button type="submit" class="btn login-btn">login</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </section>

    </main>

    <script src="{% static 'web/js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'web/js/script.js' %}"></script>
</body>

</html>